services:
  gitlab:
    image: gitlab/gitlab-ce:latest
    volumes:
      - gitlab_config:/etc/gitlab/
      - gitlab_log:/var/log/gitlab/
      - gitlab_data:/var/opt/gitlab/
    networks:
      - main

volumes:
  gitlab_config:
  gitlab_log:
  gitlab_data:

networks:
  main:
    driver: bridge
  mediawiki:
    driver: bridge
  nextcloud:
    driver: bridge
